### ISSUE TITLE
stolen sprite from ohio

### ISSUE THREAD

**Issue by MQ-1175** [Beanzilla/mindustry-hacked#17]
![image](https://github.com/Beanzilla/mindustry-hacked/assets/85242532/cd65ca1d-dfc5-4aa1-9a4f-211c486f6b79)
![image](https://github.com/Beanzilla/mindustry-hacked/assets/85242532/66c2133d-c3f7-4e29-9d3b-79aee1aaccef)

**Comment by Beanzilla** [comment]
Congrats... I'm discontinuing this mod.
